language: python

python:
 - "3.6"

sudo: required

install:
 - pip install coveralls

script:
 - coverage run --source=scripts setup.py tests

after_success:
 - coveralls

notifications:
 email: false
