language: python

python:
 - "3.6"

sudo: required

install:
 - pip install -r requirements.txt
 - pip install -e .
 - pip install coveralls

script:
 - python3 -m pytest --capture=sys

after_success:
 - coveralls

notifications:
 email: false
