language: python

python:
 - "3.6"

sudo: required

install:
 - pip install -r requirements.txt
 - pip install -e .
 - pip install coveralls

script:
 - coverage run --source=scripts setup.py test

after_success:
 - coveralls

notifications:
 email: false
